### ISSUE TITLE
pip install script broken

### ISSUE THREAD

**Issue by pventuzelo** [quoscient/octopus#5]
```
Traceback (most recent call last):
  File "/usr/local/bin/octopus_eth_evm", line 11, in <module>
    load_entry_point('octopus==0.3.2', 'console_scripts', 'octopus_eth_evm')()
  File "/home/scop/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/scop/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/scop/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/scop/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'octopus_eth_evm'
```

**Comment by pventuzelo** [comment]
master edace66
TODO: push new version on Pypi

**Comment by pventuzelo** [comment]
Done: https://pypi.org/project/octopus/0.3.3/#history
